Anous: 0.4
Brown Booby: 0.6
Brown Booby Empty Nest: 0.8
Brown Noddy: 0.45
Crested Tern Adult: 0.45
Crested Tern Other: 0.8
Crested Tern Young: 0.3
Egret: 0.45
Great Frigatebird: 0.5
Greater Crested Tern: 0.45
Noddy Species: 0.35
Onychoprion: 0.45
Ruddy Turnstone: 0.35
Silver Gull: 0.45
Sterna: 0.4
Unknown: 0.5
