Anous: 0
Brown Booby: 1
Brown Booby Empty Nest: 2
Brown Noddy: 3
Crested Tern Adult: 4
Crested Tern Other: 5
Crested Tern Young: 6
Egret: 7
Great Frigatebird: 8
Greater Crested Tern: 9
Noddy Species: 10
Onychoprion: 11
Ruddy Turnstone: 12
Silver Gull: 13
Sterna: 14
Unknown: 15
